name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build and Test operator
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2

      - name: Install helm unittest plugin
        run: |
          echo "$(awk -F':' '$0 ~ /HELM_UNITTEST_VERSION/ { print $3 }')"
          helm version
          helm plugin install https://github.com/helm-unittest/helm-unittest \
            --version "$(awk -F':' '$0 ~ /HELM_UNITTEST_VERSION/ { print $3 }')"
